/** Shared shape + loader for regions.json (generated by gen-catalog.ts, checked in). */

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

export const CATALOG_PATH = join(dirname(fileURLToPath(import.meta.url)), "..", "regions.json");

export type CatalogEntry = {
  slug: string;
  geofabrikId: string;
  name: string;
  group: string;
  groupName: string;
  /** Country name baked into geocode admin context. Absent for multi-country combos. */
  country?: string;
  /** Continent root slug — enables batch --continent filtering. */
  continent: string;
  pbfUrl: string;
  cityLevelMax?: number;
};

export function loadCatalog(path: string = CATALOG_PATH): CatalogEntry[] {
  const parsed = JSON.parse(readFileSync(path, "utf8")) as { regions: CatalogEntry[] };
  return parsed.regions;
}
